version: '3'
services:
  db:
    container_name: postgres
    image: postgres
    tty: true
    ports:
      - "0.0.0.0:27018:5432"
    volumes:
      - /root/docker/var/lib/postgresql:/var/lib/postgresql
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}